version: "3.7"

services:
  skilltracker:
    image: skilltracker
    working_dir: /var/www/node-template
    ports:
      - "30333:30333"
      - "9933:9933"
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "./scripts/process.sh"
